config/routes.rb
Rails.application.routes.draw do
  
  resources :titles
  devise_for :users
  root to: "gossip#index"
  
  get "public", to: 'gossip#index'

  get "secret", to: 'secret#index'

  get "really_secret", to: 'secret#really_secret'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role?(:admin)
        can :manage, :all
    else
        can :read, Title
    end

  end  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  has_one :guest
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :comment
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  has_many :comments
  has_many :tags

  #scope :one_week_before, -> (time) { where(published_at: time.ago(1.week)..time ) }

  scope :in_the_last_week, -> { one_week_before(Time.zone.now) }

  #scope :in_the_last_week, -> { where(published_at: (Time.zone.now-7.days..Time.zone.now) }

  #scope :in_the_last_week, -> { where('posts.published_at > ?', Time.zone.now-7.days )}

  scope :published, -> { where('posts.published_at is not null')}

  scope :commented, -> { joins(:comments).group('comments.post_id').having('count(comments.post_id) > 0')}

  scope :published_and_commented, -> { published.commented }

  def self.one_week_before(time)
    if [true,false].sample
      where(published_at: time.ago(1.week)..time )
    else
      all
    end
  end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
end

app/models/title.rb
class Title < ActiveRecord::Base
  mount_uploader :title_image, TitleImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def role?(role_to_compare_to)
    role_to_compare_to.to_s == self.role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: "You can't access that page"

  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def index
  end
end

app/controllers/secret_controller.rb
class SecretController < ApplicationController

  before_filter :authenticate_user!

  def index
  end

  def really_secret
  end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  before_action :set_title, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  # GET /titles
  # GET /titles.json
  def index
    @titles = Title.all
  end

  # GET /titles/1
  # GET /titles/1.json
  def show
  end

  # GET /titles/new
  def new
    @title = Title.new
  end

  # GET /titles/1/edit
  def edit
    authorize! :edit, @title
  end

  # POST /titles
  # POST /titles.json
  def create
    @title = Title.new(title_params)

    respond_to do |format|
      if @title.save
        format.html { redirect_to @title, notice: 'Title was successfully created.' }
        format.json { render :show, status: :created, location: @title }
      else
        format.html { render :new }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titles/1
  # PATCH/PUT /titles/1.json
  def update
    respond_to do |format|
      if @title.update(title_params)
        format.html { redirect_to @title, notice: 'Title was successfully updated.' }
        format.json { render :show, status: :ok, location: @title }
      else
        format.html { render :edit }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titles/1
  # DELETE /titles/1.json
  def destroy
    @title.destroy
    respond_to do |format|
      format.html { redirect_to titles_url, notice: 'Title was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_title
      @title = Title.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def title_params
      params.require(:title).permit(:name, :title_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/secret_helper.rb
module SecretHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/gossip/index.html.erb
<h1>Gossip#index</h1>
<p>Shout it out from the rooftops!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CX3MDB</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<nav>
  <ul>
  <li>
    <% if user_signed_in? %>
      <%= link_to 'logout', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'login', new_user_session_path %> |
      <%= link_to 'register', new_user_registration_path %>
    <% end %>
  </li>
    <li>
      <%= link_to 'gossip', public_path %>
    </li>
    <li>
      <%= link_to 'secret', secret_path %>
    </li>
    <li>
      <%= link_to 'really_secret', really_secret_path %>
    </li>
  </ul>
<nav>

<%= yield %>

</body>
</html>

app/views/secret/index.html.erb
<h1>Secret#index</h1>
<p>Shh! it's a sea-kwet!</p>

app/views/secret/really_secret.html.erb
<h1>Secret#really_secret</h1>
<p>Do not talk about Codeclan club.</p>

app/views/titles/_form.html.erb
<%= form_for(@title) do |f| %>
  <% if @title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@title.errors.count, "error") %> prohibited this title from being saved:</h2>

      <ul>
      <% @title.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
  <%= f.label :title_image %><br />
  <%= f.file_field :title_image %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/titles/edit.html.erb
<h1>Editing Title</h1>

<%= render 'form' %>

<%= link_to 'Show', @title %> |
<%= link_to 'Back', titles_path %>

app/views/titles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Titles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @titles.each do |title| %>
      <tr>
        <td><%= title.name %></td>
        <td><%= link_to image_tag(title.title_image.thumb.url), title.title_image.medium.url %></td>
        <td><%= link_to 'Show', title %></td>
        <td><%= link_to 'Edit', edit_title_path(title) %></td>
        <td><%= link_to 'Destroy', title, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Title', new_title_path %>

app/views/titles/new.html.erb
<h1>New Title</h1>

<%= render 'form' %>

<%= link_to 'Back', titles_path %>

app/views/titles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @title.name %>
</p>

<p>
<b>Image:</b>
<%= link_to image_tag(@title.title_image.thumb.url), @title.title_image.medium.url %>
</p>

<%= link_to 'Edit', edit_title_path(@title) %> |
<%= link_to 'Back', titles_path %>